# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(824, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 491, 51))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 20, 271, 22))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pathAddress = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.pathAddress.setObjectName("pathAddress")
        self.horizontalLayout.addWidget(self.pathAddress)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(300, 20, 158, 25))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fileSelectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.fileSelectButton.setObjectName("fileSelectButton")
        self.horizontalLayout_3.addWidget(self.fileSelectButton)
        self.selectFolder = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.selectFolder.setObjectName("selectFolder")
        self.horizontalLayout_3.addWidget(self.selectFolder)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 310, 521, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.outputGraph = PlotWidget(self.frame_2)
        self.outputGraph.setGeometry(QtCore.QRect(0, 0, 511, 251))
        self.outputGraph.setObjectName("outputGraph")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 80, 251, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 50, 81, 21))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(100, 20, 141, 22))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.fftWndChng = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.fftWndChng.setObjectName("fftWndChng")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.fftWndChng.addItem("")
        self.horizontalLayout_13.addWidget(self.fftWndChng)
        self.horizontalLayoutWidget_15 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(100, 50, 141, 22))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.sampleRateChng = QtWidgets.QLineEdit(self.horizontalLayoutWidget_15)
        self.sampleRateChng.setAlignment(QtCore.Qt.AlignCenter)
        self.sampleRateChng.setObjectName("sampleRateChng")
        self.horizontalLayout_15.addWidget(self.sampleRateChng)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(100, 80, 141, 22))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.fftSize = QtWidgets.QLineEdit(self.horizontalLayoutWidget_18)
        self.fftSize.setAlignment(QtCore.Qt.AlignCenter)
        self.fftSize.setObjectName("fftSize")
        self.horizontalLayout_18.addWidget(self.fftSize)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(100, 110, 56, 22))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.xLower = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.xLower.setObjectName("xLower")
        self.horizontalLayout_5.addWidget(self.xLower)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(160, 110, 21, 21))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(190, 110, 56, 22))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.xUpper = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.xUpper.setObjectName("xUpper")
        self.horizontalLayout_10.addWidget(self.xUpper)
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(160, 140, 21, 21))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(100, 140, 56, 22))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.xOLower = QtWidgets.QLineEdit(self.horizontalLayoutWidget_14)
        self.xOLower.setObjectName("xOLower")
        self.horizontalLayout_14.addWidget(self.xOLower)
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(190, 140, 56, 22))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.xOUpper = QtWidgets.QLineEdit(self.horizontalLayoutWidget_16)
        self.xOUpper.setObjectName("xOUpper")
        self.horizontalLayout_16.addWidget(self.xOUpper)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 140, 81, 21))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_17.addWidget(self.label_7)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 521, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.inputGraph = PlotWidget(self.frame)
        self.inputGraph.setGeometry(QtCore.QRect(0, 0, 511, 211))
        self.inputGraph.setObjectName("inputGraph")
        self.verticalLayout.addWidget(self.frame)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(550, 250, 251, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 211, 111))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.runFFT = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runFFT.sizePolicy().hasHeightForWidth())
        self.runFFT.setSizePolicy(sizePolicy)
        self.runFFT.setObjectName("runFFT")
        self.verticalLayout_4.addWidget(self.runFFT)
        self.runAutoCorr = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAutoCorr.sizePolicy().hasHeightForWidth())
        self.runAutoCorr.setSizePolicy(sizePolicy)
        self.runAutoCorr.setObjectName("runAutoCorr")
        self.verticalLayout_4.addWidget(self.runAutoCorr)
        self.runPowerSpectrum = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runPowerSpectrum.sizePolicy().hasHeightForWidth())
        self.runPowerSpectrum.setSizePolicy(sizePolicy)
        self.runPowerSpectrum.setObjectName("runPowerSpectrum")
        self.verticalLayout_4.addWidget(self.runPowerSpectrum)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(600, 490, 161, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.exitButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout_3.addWidget(self.exitButton)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(550, 540, 261, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(600, 10, 161, 61))
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.playButton = QtWidgets.QPushButton(self.groupBox_4)
        self.playButton.setGeometry(QtCore.QRect(20, 20, 41, 31))
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/26025.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setObjectName("playButton")
        self.pauseButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pauseButton.setGeometry(QtCore.QRect(60, 20, 41, 31))
        self.pauseButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/61039.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon1)
        self.pauseButton.setObjectName("pauseButton")
        self.stopButton = QtWidgets.QPushButton(self.groupBox_4)
        self.stopButton.setGeometry(QtCore.QRect(100, 20, 41, 31))
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/player-stop-outline-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(16, 16))
        self.stopButton.setObjectName("stopButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(550, 410, 251, 71))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 221, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.batchAnalysis = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchAnalysis.sizePolicy().hasHeightForWidth())
        self.batchAnalysis.setSizePolicy(sizePolicy)
        self.batchAnalysis.setObjectName("batchAnalysis")
        self.horizontalLayout_2.addWidget(self.batchAnalysis)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hansmaurer Spectralizer"))
        self.groupBox.setTitle(_translate("MainWindow", "Choose Wave File/Directory"))
        self.fileSelectButton.setText(_translate("MainWindow", "Select File"))
        self.selectFolder.setText(_translate("MainWindow", "Select Folder"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Analysis Parameter"))
        self.label_4.setText(_translate("MainWindow", "FFT Window"))
        self.label_6.setText(_translate("MainWindow", "Sample Rate"))
        self.fftWndChng.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.fftWndChng.setItemText(1, _translate("MainWindow", "Hanning"))
        self.fftWndChng.setItemText(2, _translate("MainWindow", "Hamming"))
        self.fftWndChng.setItemText(3, _translate("MainWindow", "Kaiser"))
        self.fftWndChng.setItemText(4, _translate("MainWindow", "Nuttall"))
        self.fftWndChng.setItemText(5, _translate("MainWindow", "Parzen"))
        self.fftWndChng.setItemText(6, _translate("MainWindow", "Blackman"))
        self.fftWndChng.setItemText(7, _translate("MainWindow", "Flattop"))
        self.fftWndChng.setItemText(8, _translate("MainWindow", "Dolph-Chebyshev"))
        self.sampleRateChng.setText(_translate("MainWindow", "44100"))
        self.label_5.setText(_translate("MainWindow", "FFT Size"))
        self.fftSize.setText(_translate("MainWindow", "1024"))
        self.label.setText(_translate("MainWindow", "WAV X range"))
        self.xLower.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "To"))
        self.xUpper.setText(_translate("MainWindow", "30000"))
        self.label_3.setText(_translate("MainWindow", "To"))
        self.xOLower.setText(_translate("MainWindow", "0"))
        self.xOUpper.setText(_translate("MainWindow", "4000"))
        self.label_7.setText(_translate("MainWindow", "Output X range"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Primary Analysis"))
        self.runFFT.setText(_translate("MainWindow", "Run FFT"))
        self.runAutoCorr.setText(_translate("MainWindow", "Autocorrelation"))
        self.runPowerSpectrum.setText(_translate("MainWindow", "Power Spectrum"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Play WAV file"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Batch Analysis"))
        self.batchAnalysis.setText(_translate("MainWindow", "Run AC and FFT batch analysis"))

from pyqtgraph import PlotWidget
